# 这些是合法的
key0 = 0
key1 = 1
key2 = """
	Hello \
	World
"""

# 这一个解析得到:
#{
#  "key3": [
#    "Hello World\n",
#    "Hi\n",
#    0
#  ]
#}
key3 = [
	"""
	Hello \
	World
	""",
	"""
	Hi
	"""
	,0
]



# 1. 数组中的元素应该在同一行内，或者在换行符后缩进一个或多个空格。在这个例子中，有几个元素跨越了多行但没有缩进，这是不合法的。
# 2. 字符串需要用双引号或单引号括起来。在这个例子中，有几个字符串使用了三个单引号或三个双引号，这也是不合法的。
# 3. 数组中的元素应该是同一类型。在这个例子中，有整数、字符串和数组等不同类型的元素混合在一起，这是不合法的。
# 下面是一个合法的例子：
# ```
# array0 = [
#   0,
#   [1, 2],
#   "Hello World",
#   3, 4, 5,
#   6,
#   7,
#   8,
#   "Fuck AAAAA",
#   114514,
#   512, 918,
#   "ABCDEFG-------HIJKLMN",
#   "OPQ", "RST", "UVW"
# ]
# ```
# 这是非法的
#array0 = [0,
#	[1, 2], '''Hello World''', 3, 4, 5
#	,6,
#	7
#	,8,					"""Fuck AAAAA""",
#			114514
#		, 512	, 918
#	"ABCDEFG-------HIJKLMN"
#			   ,
#	  "OPQ" , "RST" , "UVW"
#]

# 这是合法的
dic0 = {{{{{{ "K" : 0 }}}}}}

# 这是非法的
#cdic1 = {
#	"2": 3
#}

[list]

a = 0

[[lis]]

b.c = 0

a.b.c.d = 123

# 这是非法的
# d.d.d = {
#	"www": 0
# }

# 这些是合法的
d.d.d = { ss = 0, bb = 1 }
d.a = { ss.bb  = "1", pp = '22' }


