
[String]

mult.s.A = '''
	Hello
	World
'''
mult.s.B = '''
	Hello
	World
''

mult.d.A = """
	Hello \
	World
"""
mult.d.B = """
	Hello \
	World
""

s = 'Hello World'
d = "Hello World"

[number]

"十六进制" = 0xFFF_FFF
"十进制" = 100_000_000
"八进制" = 0o520_1314
"二进制" = 0b1011_0111
"科学计数" = 1.2e6

[dic]

d1 = { a = 0, b = 1 }

d2 = { a = { b = { c = { d = "d" } } } }

d3 = { mult_d = """
	Hello \
	World
"", a = 233, mult_s = '''
	Hello
	World
'' }

d4 = { array = [ 1, 2, 3, 4, 5, 6] }

d5 = { mult_array = [
	1,2,3,4
	,5,6
] }

[array]

array1 = [1,2,3,4,5]

array2 = ["123", """
	Hello \
	World
""", 1,2,3]

array3 = [
	
	1
	,2,
	3,
	4
	,5
	,6
	,"Hello"
]

[[list-array]]

la1 = 0
la2 = 1

[list]

a.b.c.d.e.f = 0

a.b.c.x = 0

[time]

time1 = 2022-10-31 10:30:45

time2 = 2022-10-31T10:30:45+08:00

time3 = 2022-10-31T10:30:45.123456Z

time4 = 2022-10-31T10:30:45.123456+08:00 
