
#dic = { k1=0, k2 = 0, k3 = { kk1 = { k	kk = [1	0,"1" 	  ,2,3,4,"5"] } } }

# 值得注意的是：
# "内联表不允许换行，除非换行在值内是合法的"
# 也就是说，内联的多行是合法的
# TODO
#"中文".dic2.ss.		rr. tt ."pp\t" = { str_m_d = """
#	Hello \
#	
#	World
#"", str_m_s.kk = '''
#	Hello \
#	World
#'' }#2333
# PASS
#dic3 = [{ a.b = 0, a.c = { b.a = 0, b .b = 1 } }, 9]

# 以下是错误例子

# 这个例子中的错误:
# a.b.c = { ff = 0 }
# 已经定义了一个 c 作为末端
# 末端是不可以被后面的来修改的
# a.b.c.e
#     ^
# 这里延伸的 e 是错误的
# PASS
#dic4 = { a.b.c = { o = 0 }, a.b.c.e = 0  }

# 这个例子中的错误:
# a.b.c 已经定义，并且 c 已经注册为 路径的末尾值
# 再次定义是错误的
# PASS
#dic5 = { a. b.c = 1, a.b.c = 2 }

#dic6 = { a.b = 0, b.c = { a.0 = 1 }, c.d = [1,2,3,4] }

#arr = [1,2,3, [9,0, {0 = {1 = {2 = 3} } } ] ]

#dic7 = { 0 = { 1 = { 2 = { 3 = { 4.2 = 2, 4.1 = "str" } } } } }

#[ list ]

# 这是错误的
#dic7 = [
#	{ 
#		key = 0
#	},
#	{ key = [
#		0, 1,2]
#	}
#	,{
#		key = 0}
#]

dic8 = { arr = [
	0, 1, 2,3,4, """
		Hello \
		World
	"", 2022-10-31T10:30:45Z
] }

time = 2022-10-31T10:30:45Z
